//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace GoDutchServer.Model
{
    #region 上下文
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    public partial class Sanwai_CustEntities : ObjectContext
    {
        #region 构造函数
    
        /// <summary>
        /// 请使用应用程序配置文件的“Sanwai_CustEntities”部分中的连接字符串初始化新 Sanwai_CustEntities 对象。
        /// </summary>
        public Sanwai_CustEntities() : base("name=Sanwai_CustEntities", "Sanwai_CustEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 Sanwai_CustEntities 对象。
        /// </summary>
        public Sanwai_CustEntities(string connectionString) : base(connectionString, "Sanwai_CustEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 Sanwai_CustEntities 对象。
        /// </summary>
        public Sanwai_CustEntities(EntityConnection connection) : base(connection, "Sanwai_CustEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 分部方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<Stock> Stocks
        {
            get
            {
                if ((_Stocks == null))
                {
                    _Stocks = base.CreateObjectSet<Stock>("Stocks");
                }
                return _Stocks;
            }
        }
        private ObjectSet<Stock> _Stocks;

        #endregion

        #region AddTo 方法
    
        /// <summary>
        /// 用于向 Stocks EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToStocks(Stock stock)
        {
            base.AddObject("Stocks", stock);
        }

        #endregion

    }

    #endregion

    #region 实体
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Sanwai_CustModel", Name="Stock")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Stock : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 Stock 对象。
        /// </summary>
        /// <param name="id">Id 属性的初始值。</param>
        public static Stock CreateStock(global::System.Int32 id)
        {
            Stock stock = new Stock();
            stock.Id = id;
            return stock;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String stock1
        {
            get
            {
                return _stock1;
            }
            set
            {
                Onstock1Changing(value);
                ReportPropertyChanging("stock1");
                _stock1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("stock1");
                Onstock1Changed();
            }
        }
        private global::System.String _stock1;
        partial void Onstock1Changing(global::System.String value);
        partial void Onstock1Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String vref
        {
            get
            {
                return _vref;
            }
            set
            {
                OnvrefChanging(value);
                ReportPropertyChanging("vref");
                _vref = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("vref");
                OnvrefChanged();
            }
        }
        private global::System.String _vref;
        partial void OnvrefChanging(global::System.String value);
        partial void OnvrefChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String partno
        {
            get
            {
                return _partno;
            }
            set
            {
                OnpartnoChanging(value);
                ReportPropertyChanging("partno");
                _partno = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("partno");
                OnpartnoChanged();
            }
        }
        private global::System.String _partno;
        partial void OnpartnoChanging(global::System.String value);
        partial void OnpartnoChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String barcode
        {
            get
            {
                return _barcode;
            }
            set
            {
                OnbarcodeChanging(value);
                ReportPropertyChanging("barcode");
                _barcode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("barcode");
                OnbarcodeChanged();
            }
        }
        private global::System.String _barcode;
        partial void OnbarcodeChanging(global::System.String value);
        partial void OnbarcodeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> active
        {
            get
            {
                return _active;
            }
            set
            {
                OnactiveChanging(value);
                ReportPropertyChanging("active");
                _active = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("active");
                OnactiveChanged();
            }
        }
        private Nullable<global::System.Boolean> _active;
        partial void OnactiveChanging(Nullable<global::System.Boolean> value);
        partial void OnactiveChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String serialno
        {
            get
            {
                return _serialno;
            }
            set
            {
                OnserialnoChanging(value);
                ReportPropertyChanging("serialno");
                _serialno = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("serialno");
                OnserialnoChanged();
            }
        }
        private global::System.String _serialno;
        partial void OnserialnoChanging(global::System.String value);
        partial void OnserialnoChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> maincate
        {
            get
            {
                return _maincate;
            }
            set
            {
                OnmaincateChanging(value);
                ReportPropertyChanging("maincate");
                _maincate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("maincate");
                OnmaincateChanged();
            }
        }
        private Nullable<global::System.Int32> _maincate;
        partial void OnmaincateChanging(Nullable<global::System.Int32> value);
        partial void OnmaincateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String des
        {
            get
            {
                return _des;
            }
            set
            {
                OndesChanging(value);
                ReportPropertyChanging("des");
                _des = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("des");
                OndesChanged();
            }
        }
        private global::System.String _des;
        partial void OndesChanging(global::System.String value);
        partial void OndesChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String shortdes
        {
            get
            {
                return _shortdes;
            }
            set
            {
                OnshortdesChanging(value);
                ReportPropertyChanging("shortdes");
                _shortdes = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("shortdes");
                OnshortdesChanged();
            }
        }
        private global::System.String _shortdes;
        partial void OnshortdesChanging(global::System.String value);
        partial void OnshortdesChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String unit
        {
            get
            {
                return _unit;
            }
            set
            {
                OnunitChanging(value);
                ReportPropertyChanging("unit");
                _unit = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("unit");
                OnunitChanged();
            }
        }
        private global::System.String _unit;
        partial void OnunitChanging(global::System.String value);
        partial void OnunitChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String category
        {
            get
            {
                return _category;
            }
            set
            {
                OncategoryChanging(value);
                ReportPropertyChanging("category");
                _category = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("category");
                OncategoryChanged();
            }
        }
        private global::System.String _category;
        partial void OncategoryChanging(global::System.String value);
        partial void OncategoryChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String brand
        {
            get
            {
                return _brand;
            }
            set
            {
                OnbrandChanging(value);
                ReportPropertyChanging("brand");
                _brand = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("brand");
                OnbrandChanged();
            }
        }
        private global::System.String _brand;
        partial void OnbrandChanging(global::System.String value);
        partial void OnbrandChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String costcurr
        {
            get
            {
                return _costcurr;
            }
            set
            {
                OncostcurrChanging(value);
                ReportPropertyChanging("costcurr");
                _costcurr = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("costcurr");
                OncostcurrChanged();
            }
        }
        private global::System.String _costcurr;
        partial void OncostcurrChanging(global::System.String value);
        partial void OncostcurrChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String pricecurr
        {
            get
            {
                return _pricecurr;
            }
            set
            {
                OnpricecurrChanging(value);
                ReportPropertyChanging("pricecurr");
                _pricecurr = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("pricecurr");
                OnpricecurrChanged();
            }
        }
        private global::System.String _pricecurr;
        partial void OnpricecurrChanging(global::System.String value);
        partial void OnpricecurrChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> cost
        {
            get
            {
                return _cost;
            }
            set
            {
                OncostChanging(value);
                ReportPropertyChanging("cost");
                _cost = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("cost");
                OncostChanged();
            }
        }
        private Nullable<global::System.Double> _cost;
        partial void OncostChanging(Nullable<global::System.Double> value);
        partial void OncostChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> price
        {
            get
            {
                return _price;
            }
            set
            {
                OnpriceChanging(value);
                ReportPropertyChanging("price");
                _price = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("price");
                OnpriceChanged();
            }
        }
        private Nullable<global::System.Double> _price;
        partial void OnpriceChanging(Nullable<global::System.Double> value);
        partial void OnpriceChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> delaprice
        {
            get
            {
                return _delaprice;
            }
            set
            {
                OndelapriceChanging(value);
                ReportPropertyChanging("delaprice");
                _delaprice = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("delaprice");
                OndelapriceChanged();
            }
        }
        private Nullable<global::System.Double> _delaprice;
        partial void OndelapriceChanging(Nullable<global::System.Double> value);
        partial void OndelapriceChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> btnprice
        {
            get
            {
                return _btnprice;
            }
            set
            {
                OnbtnpriceChanging(value);
                ReportPropertyChanging("btnprice");
                _btnprice = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("btnprice");
                OnbtnpriceChanged();
            }
        }
        private Nullable<global::System.Double> _btnprice;
        partial void OnbtnpriceChanging(Nullable<global::System.Double> value);
        partial void OnbtnpriceChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String vendor
        {
            get
            {
                return _vendor;
            }
            set
            {
                OnvendorChanging(value);
                ReportPropertyChanging("vendor");
                _vendor = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("vendor");
                OnvendorChanged();
            }
        }
        private global::System.String _vendor;
        partial void OnvendorChanging(global::System.String value);
        partial void OnvendorChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String vendorname
        {
            get
            {
                return _vendorname;
            }
            set
            {
                OnvendornameChanging(value);
                ReportPropertyChanging("vendorname");
                _vendorname = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("vendorname");
                OnvendornameChanged();
            }
        }
        private global::System.String _vendorname;
        partial void OnvendornameChanging(global::System.String value);
        partial void OnvendornameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> cbalqty
        {
            get
            {
                return _cbalqty;
            }
            set
            {
                OncbalqtyChanging(value);
                ReportPropertyChanging("cbalqty");
                _cbalqty = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("cbalqty");
                OncbalqtyChanged();
            }
        }
        private Nullable<global::System.Double> _cbalqty;
        partial void OncbalqtyChanging(Nullable<global::System.Double> value);
        partial void OncbalqtyChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> stktake
        {
            get
            {
                return _stktake;
            }
            set
            {
                OnstktakeChanging(value);
                ReportPropertyChanging("stktake");
                _stktake = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("stktake");
                OnstktakeChanged();
            }
        }
        private Nullable<global::System.Double> _stktake;
        partial void OnstktakeChanging(Nullable<global::System.Double> value);
        partial void OnstktakeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> onholdqty
        {
            get
            {
                return _onholdqty;
            }
            set
            {
                OnonholdqtyChanging(value);
                ReportPropertyChanging("onholdqty");
                _onholdqty = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("onholdqty");
                OnonholdqtyChanged();
            }
        }
        private Nullable<global::System.Double> _onholdqty;
        partial void OnonholdqtyChanging(Nullable<global::System.Double> value);
        partial void OnonholdqtyChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> rmaqty
        {
            get
            {
                return _rmaqty;
            }
            set
            {
                OnrmaqtyChanging(value);
                ReportPropertyChanging("rmaqty");
                _rmaqty = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("rmaqty");
                OnrmaqtyChanged();
            }
        }
        private Nullable<global::System.Double> _rmaqty;
        partial void OnrmaqtyChanging(Nullable<global::System.Double> value);
        partial void OnrmaqtyChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> purqty
        {
            get
            {
                return _purqty;
            }
            set
            {
                OnpurqtyChanging(value);
                ReportPropertyChanging("purqty");
                _purqty = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("purqty");
                OnpurqtyChanged();
            }
        }
        private Nullable<global::System.Double> _purqty;
        partial void OnpurqtyChanging(Nullable<global::System.Double> value);
        partial void OnpurqtyChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> minqty
        {
            get
            {
                return _minqty;
            }
            set
            {
                OnminqtyChanging(value);
                ReportPropertyChanging("minqty");
                _minqty = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("minqty");
                OnminqtyChanged();
            }
        }
        private Nullable<global::System.Double> _minqty;
        partial void OnminqtyChanging(Nullable<global::System.Double> value);
        partial void OnminqtyChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> maxqty
        {
            get
            {
                return _maxqty;
            }
            set
            {
                OnmaxqtyChanging(value);
                ReportPropertyChanging("maxqty");
                _maxqty = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("maxqty");
                OnmaxqtyChanged();
            }
        }
        private Nullable<global::System.Double> _maxqty;
        partial void OnmaxqtyChanging(Nullable<global::System.Double> value);
        partial void OnmaxqtyChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String rem
        {
            get
            {
                return _rem;
            }
            set
            {
                OnremChanging(value);
                ReportPropertyChanging("rem");
                _rem = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("rem");
                OnremChanged();
            }
        }
        private global::System.String _rem;
        partial void OnremChanging(global::System.String value);
        partial void OnremChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String rem2
        {
            get
            {
                return _rem2;
            }
            set
            {
                Onrem2Changing(value);
                ReportPropertyChanging("rem2");
                _rem2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("rem2");
                Onrem2Changed();
            }
        }
        private global::System.String _rem2;
        partial void Onrem2Changing(global::System.String value);
        partial void Onrem2Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> createdate
        {
            get
            {
                return _createdate;
            }
            set
            {
                OncreatedateChanging(value);
                ReportPropertyChanging("createdate");
                _createdate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("createdate");
                OncreatedateChanged();
            }
        }
        private Nullable<global::System.DateTime> _createdate;
        partial void OncreatedateChanging(Nullable<global::System.DateTime> value);
        partial void OncreatedateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> cost_wa_dt
        {
            get
            {
                return _cost_wa_dt;
            }
            set
            {
                Oncost_wa_dtChanging(value);
                ReportPropertyChanging("cost_wa_dt");
                _cost_wa_dt = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("cost_wa_dt");
                Oncost_wa_dtChanged();
            }
        }
        private Nullable<global::System.DateTime> _cost_wa_dt;
        partial void Oncost_wa_dtChanging(Nullable<global::System.DateTime> value);
        partial void Oncost_wa_dtChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> cost_wa
        {
            get
            {
                return _cost_wa;
            }
            set
            {
                Oncost_waChanging(value);
                ReportPropertyChanging("cost_wa");
                _cost_wa = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("cost_wa");
                Oncost_waChanged();
            }
        }
        private Nullable<global::System.Double> _cost_wa;
        partial void Oncost_waChanging(Nullable<global::System.Double> value);
        partial void Oncost_waChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> totcos_wa
        {
            get
            {
                return _totcos_wa;
            }
            set
            {
                Ontotcos_waChanging(value);
                ReportPropertyChanging("totcos_wa");
                _totcos_wa = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("totcos_wa");
                Ontotcos_waChanged();
            }
        }
        private Nullable<global::System.Double> _totcos_wa;
        partial void Ontotcos_waChanging(Nullable<global::System.Double> value);
        partial void Ontotcos_waChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String picfile
        {
            get
            {
                return _picfile;
            }
            set
            {
                OnpicfileChanging(value);
                ReportPropertyChanging("picfile");
                _picfile = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("picfile");
                OnpicfileChanged();
            }
        }
        private global::System.String _picfile;
        partial void OnpicfileChanging(global::System.String value);
        partial void OnpicfileChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String power
        {
            get
            {
                return _power;
            }
            set
            {
                OnpowerChanging(value);
                ReportPropertyChanging("power");
                _power = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("power");
                OnpowerChanged();
            }
        }
        private global::System.String _power;
        partial void OnpowerChanging(global::System.String value);
        partial void OnpowerChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String opowerrms
        {
            get
            {
                return _opowerrms;
            }
            set
            {
                OnopowerrmsChanging(value);
                ReportPropertyChanging("opowerrms");
                _opowerrms = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("opowerrms");
                OnopowerrmsChanged();
            }
        }
        private global::System.String _opowerrms;
        partial void OnopowerrmsChanging(global::System.String value);
        partial void OnopowerrmsChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String opowerpmpo
        {
            get
            {
                return _opowerpmpo;
            }
            set
            {
                OnopowerpmpoChanging(value);
                ReportPropertyChanging("opowerpmpo");
                _opowerpmpo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("opowerpmpo");
                OnopowerpmpoChanged();
            }
        }
        private global::System.String _opowerpmpo;
        partial void OnopowerpmpoChanging(global::System.String value);
        partial void OnopowerpmpoChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String gbbarcode
        {
            get
            {
                return _gbbarcode;
            }
            set
            {
                OngbbarcodeChanging(value);
                ReportPropertyChanging("gbbarcode");
                _gbbarcode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("gbbarcode");
                OngbbarcodeChanged();
            }
        }
        private global::System.String _gbbarcode;
        partial void OngbbarcodeChanging(global::System.String value);
        partial void OngbbarcodeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ocbarcode
        {
            get
            {
                return _ocbarcode;
            }
            set
            {
                OnocbarcodeChanging(value);
                ReportPropertyChanging("ocbarcode");
                _ocbarcode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ocbarcode");
                OnocbarcodeChanged();
            }
        }
        private global::System.String _ocbarcode;
        partial void OnocbarcodeChanging(global::System.String value);
        partial void OnocbarcodeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String pbarcode
        {
            get
            {
                return _pbarcode;
            }
            set
            {
                OnpbarcodeChanging(value);
                ReportPropertyChanging("pbarcode");
                _pbarcode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("pbarcode");
                OnpbarcodeChanged();
            }
        }
        private global::System.String _pbarcode;
        partial void OnpbarcodeChanging(global::System.String value);
        partial void OnpbarcodeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String sclass
        {
            get
            {
                return _sclass;
            }
            set
            {
                OnsclassChanging(value);
                ReportPropertyChanging("sclass");
                _sclass = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("sclass");
                OnsclassChanged();
            }
        }
        private global::System.String _sclass;
        partial void OnsclassChanging(global::System.String value);
        partial void OnsclassChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String subclass
        {
            get
            {
                return _subclass;
            }
            set
            {
                OnsubclassChanging(value);
                ReportPropertyChanging("subclass");
                _subclass = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("subclass");
                OnsubclassChanged();
            }
        }
        private global::System.String _subclass;
        partial void OnsubclassChanging(global::System.String value);
        partial void OnsubclassChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> edittime
        {
            get
            {
                return _edittime;
            }
            set
            {
                OnedittimeChanging(value);
                ReportPropertyChanging("edittime");
                _edittime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("edittime");
                OnedittimeChanged();
            }
        }
        private Nullable<global::System.Int32> _edittime;
        partial void OnedittimeChanging(Nullable<global::System.Int32> value);
        partial void OnedittimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> firstmdate
        {
            get
            {
                return _firstmdate;
            }
            set
            {
                OnfirstmdateChanging(value);
                ReportPropertyChanging("firstmdate");
                _firstmdate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("firstmdate");
                OnfirstmdateChanged();
            }
        }
        private Nullable<global::System.DateTime> _firstmdate;
        partial void OnfirstmdateChanging(Nullable<global::System.DateTime> value);
        partial void OnfirstmdateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String fusername
        {
            get
            {
                return _fusername;
            }
            set
            {
                OnfusernameChanging(value);
                ReportPropertyChanging("fusername");
                _fusername = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("fusername");
                OnfusernameChanged();
            }
        }
        private global::System.String _fusername;
        partial void OnfusernameChanging(global::System.String value);
        partial void OnfusernameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> lastmdate
        {
            get
            {
                return _lastmdate;
            }
            set
            {
                OnlastmdateChanging(value);
                ReportPropertyChanging("lastmdate");
                _lastmdate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("lastmdate");
                OnlastmdateChanged();
            }
        }
        private Nullable<global::System.DateTime> _lastmdate;
        partial void OnlastmdateChanging(Nullable<global::System.DateTime> value);
        partial void OnlastmdateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String username
        {
            get
            {
                return _username;
            }
            set
            {
                OnusernameChanging(value);
                ReportPropertyChanging("username");
                _username = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("username");
                OnusernameChanged();
            }
        }
        private global::System.String _username;
        partial void OnusernameChanging(global::System.String value);
        partial void OnusernameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Client
        {
            get
            {
                return _Client;
            }
            set
            {
                OnClientChanging(value);
                ReportPropertyChanging("Client");
                _Client = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Client");
                OnClientChanged();
            }
        }
        private global::System.String _Client;
        partial void OnClientChanging(global::System.String value);
        partial void OnClientChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Address
        {
            get
            {
                return _Address;
            }
            set
            {
                OnAddressChanging(value);
                ReportPropertyChanging("Address");
                _Address = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Address");
                OnAddressChanged();
            }
        }
        private global::System.String _Address;
        partial void OnAddressChanging(global::System.String value);
        partial void OnAddressChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DeliveryAddress
        {
            get
            {
                return _DeliveryAddress;
            }
            set
            {
                OnDeliveryAddressChanging(value);
                ReportPropertyChanging("DeliveryAddress");
                _DeliveryAddress = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DeliveryAddress");
                OnDeliveryAddressChanged();
            }
        }
        private global::System.String _DeliveryAddress;
        partial void OnDeliveryAddressChanging(global::System.String value);
        partial void OnDeliveryAddressChanged();

        #endregion

    
    }

    #endregion

    
}
